[username]
format = " [╭─$user]($style)@"
style_user = "bold green"
style_root = "bold white"
show_always = true

[hostname]
format = "[$hostname]($style) in "
style = "bold green"
trim_at = "-"
ssh_only = false
disabled = false

[directory]
style = "green"
truncation_length = 0
truncate_to_repo = true
truncation_symbol = ""

[cmd_duration]
min_time = 1
format = "took [$duration]($style)"
disabled = false

[character]
success_symbol = " [╰─>](bold green)"
error_symbol = " [×](bold green)"

[status]
symbol = "🔴"
format = '[\[$symbol$status_common_meaning$status_signal_name$status_maybe_int\]]($style)'
map_symbol = true
disabled = false

[custom.pnpm]
command = "pnpm -v"
detect_files = ["pnpm-lock.yaml"]
style = "bold fg:#f69220"
symbol = " "

[bun]
disabled = true

[custom.bun]
command = "bun -v"
detect_files = ["bun.lock", "bun.lockb", "bunfig.toml"]
style = "bold fg:#fbf0df"
symbol = " "

[custom.yarn]
command = "yarn -v"
detect_files = ["yarn.lock"]
style = "bold fg:#2188b6"
symbol = " "

[custom.npm]
command = "npm -v"
detect_files = ["package-lock.json"]
style = "bold fg:#ea2039"
symbol = " "

[dart]
symbol = " "

[docker_context]
symbol = " "

[git_branch]
symbol = " "

[golang]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[nodejs]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "

[swift]
symbol = "ﯣ "
